### ISSUE TITLE
Example code gives error: AttributeError: 'Plot_OldSync' object has no attribute 'mpyplot'

### ISSUE THREAD

**Issue by mtucker502** [alpacahq/alpaca-backtrader-api#110]
I'm running the sample code from README and I receive this error:

```bash
$ python bt_alpaca.py
Starting Portfolio Value: 10000.00
Traceback (most recent call last):
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/alpaca_backtrader_api/alpacastore.py", line 405, in _t_candles
    cdl = self.get_aggs_from_alpaca(dataname,
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/alpaca_backtrader_api/alpacastore.py", line 659, in get_aggs_from_alpaca
    response = _iterate_api_calls()
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/alpaca_backtrader_api/alpacastore.py", line 590, in _iterate_api_calls
    if earliest_sample <= pytz.timezone(NY).localize(start):
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/pytz/tzinfo.py", line 318, in localize
    raise ValueError('Not naive datetime (tzinfo is already set)')
ValueError: Not naive datetime (tzinfo is already set)
Final Portfolio Value: 10000.00
Traceback (most recent call last):
  File "bt_alpaca.py", line 45, in <module>
    cerebro.plot()
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/backtrader/cerebro.py", line 996, in plot
    plotter.show()
  File "/home/spider/backtrader/venv/lib/python3.8/site-packages/backtrader/plot/plot.py", line 817, in show
    self.mpyplot.show()
AttributeError: 'Plot_OldSync' object has no attribute 'mpyplot'
```

Here are the packages I have installed:
```bash
alpaca-backtrader-api==0.10.0
alpaca-trade-api==0.50.1
astroid==2.4.2
backtrader==1.9.76.123
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
idna==2.10
isort==5.4.2
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
matplotlib==3.2.2
mccabe==0.6.1
numpy==1.19.1
pandas==1.1.1
Pillow==7.2.0
pylint==2.6.0
pyparsing==2.4.7
python-dateutil==2.8.1
python-dotenv==0.14.0
pytz==2020.1
requests==2.24.0
six==1.15.0
toml==0.10.1
toolz==0.10.0
trading-calendars==1.11.10
urllib3==1.25.10
websocket-client==0.57.0
websockets==8.1
wrapt==1.12.1
```

This is the same as #47.

**Comment by shlomikushchi** [comment]
Hi.
This is the exact same issue as: https://github.com/alpacahq/alpaca-backtrader-api/issues/107
package was fixed, not yet released to pypi.
you can install the fixed version directly from girhub or wait for it to be released.
you can install it like this:
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api`

**Comment by mtucker502** [comment]
Can confirm latest commit fixes this issue.

I pulled latest (10.0) from earlier in the day yesterday but it didn't have this fix in it yet.

Thank you for the update.
