### ISSUE TITLE
ImportError: cannot import name 'warnings

### ISSUE THREAD

**Issue by x777** [alpacahq/alpaca-backtrader-api#121]
Looks like something missing with plotting.
I am trying to use the latest version of the library and strategy from samples and have such error at the end of backtesting:
```
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    cerebro.plot()
  File "/home/user/anaconda3/envs/env_alpaca_latest/lib/python3.6/site-packages/backtrader/cerebro.py", line 974, in plot
    from . import plot
  File "/home/user/anaconda3/envs/env_alpaca_latest/lib/python3.6/site-packages/backtrader/plot/__init__.py", line 42, in <module>
    from .plot import Plot, Plot_OldSync
  File "/home/user/anaconda3/envs/env_alpaca_latest/lib/python3.6/site-packages/backtrader/plot/plot.py", line 44, in <module>
    from . import locator as loc
  File "/home/user/anaconda3/envs/env_alpaca_latest/lib/python3.6/site-packages/backtrader/plot/locator.py", line 35, in <module>
    from matplotlib.dates import (HOURS_PER_DAY, MIN_PER_HOUR, SEC_PER_MIN,
ImportError: cannot import name 'warnings'
```

pip freeze:
```
alpaca-backtrader-api==0.10.1
alpaca-trade-api==0.50.1
backtrader==1.9.76.123
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
idna==2.10
kiwisolver==1.2.0
matplotlib==3.3.2
numpy==1.19.2
pandas==1.1.3
Pillow==7.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
six==1.15.0
toolz==0.11.1
trading-calendars==1.11.11
urllib3==1.25.10
websocket-client==0.57.0
websockets==8.1
```

**Comment by shlomikushchi** [comment]
Hi, try using matplotlib==3.2.1

**Comment by x777** [comment]
Yes, it's worked with this version of matplotlib. Thanks.
