### ISSUE TITLE
No current event loop in thread when running the example

### ISSUE THREAD

**Issue by fjctp** [alpacahq/alpaca-backtrader-api#13]
I tried to run the example in README.md, but I got a "No current event loop in thread" exception.

I have the following packages installed
- Python                             3.6.8
- alpaca-backtrader-api     0.3
- alpaca-trade-api              0.35
- backtrader                       1.9.74.123

Python script that I used:
```
import backtrader as bt
import alpaca_backtrader_api

from datetime import datetime

import sceret

class SmaCross(bt.SignalStrategy):
    def __init__(self):
        sma1, sma2 = bt.ind.SMA(period=10), bt.ind.SMA(period=30)
        crossover = bt.ind.CrossOver(sma1, sma2)
        self.signal_add(bt.SIGNAL_LONG, crossover)

cerebro = bt.Cerebro()
cerebro.addstrategy(SmaCross)

store = alpaca_backtrader_api.AlpacaStore(
    key_id=sceret.api_key_id,
    secret_key=sceret.api_secret,
    paper=True
)

broker = store.getbroker()  # or just alpaca_backtrader_api.AlpacaBroker()
cerebro.setbroker(broker)

DataFactory = store.getdata # or use alpaca_backtrader_api.AlpacaData
data0 = DataFactory(dataname='AAPL', 
                    historical=True, 
                    fromdate=datetime(2015, 1,1), 
                    timeframe=bt.TimeFrame.TFrame("Days"))  # Supported timeframes: "Days"/"Minutes"
cerebro.adddata(data0)

cerebro.run(exactbars=1)
cerebro.plot()
```

The exception that I got.
```
Exception in thread Thread-97:
Traceback (most recent call last):
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 309, in _t_streaming_events
    base_url=self.p.base_url)
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 91, in __init__
    self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\site-packages\alpaca_trade_api\stream2.py", line 21, in __init__
    self.loop = asyncio.get_event_loop()
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\asyncio\events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\SomeUser\Miniconda3\envs\alpaca-trade\lib\asyncio\events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-97'.
```

**Comment by alexonab** [comment]
Try cerebro.setbroker() instead of cerebro.setbroker(broker).  It seems like the alpaca broker only works with live trading.  The default broker will do for backtesting.

**Comment by fjctp** [comment]
I tried `cerebro.setbroker()` as you suggested, but I got this error.
```
setbroker() missing 1 required positional argument: 'broker'
```

Then I removed the line `cerebro.setbroker(broker)`. The script finished without error, but I did not see a plot at the end.

**Comment by thedatadavis** [comment]
I had this issue as well.

The culprit appears to be in the alpaca-trade-api itself. Update the stream2.py module to create a new event loop if one is not running.

Change this:
```
# /site-packages/alpaca_trade_api/stream2.py
class StreamConn(object):
    def __init__(self, key_id=None, secret_key=None, base_url=None):
        self._key_id, self._secret_key = get_credentials(key_id, secret_key)
        base_url = re.sub(r'^http', 'ws', base_url or get_base_url())
        self._endpoint = base_url + '/stream'
        self._handlers = {}
        self._handler_symbols = {}
        self._base_url = base_url
        self._ws = None
        self.polygon = None
        self.loop = asyncio.get_event_loop() # where Runtime Error is occuring
```

To this:
```
# /site-packages/alpaca_trade_api/stream2.py
class StreamConn(object):
    def __init__(self, key_id=None, secret_key=None, base_url=None):
        self._key_id, self._secret_key = get_credentials(key_id, secret_key)
        base_url = re.sub(r'^http', 'ws', base_url or get_base_url())
        self._endpoint = base_url + '/stream'
        self._handlers = {}
        self._handler_symbols = {}
        self._base_url = base_url
        self._ws = None
        self.polygon = None

        # Add try block for get_event_loop()
        # If no current loop then create one
        try:
            self.loop = asyncio.get_event_loop()
        except:
            self.loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self.loop)
```

Alas, while this will run with no error, my plot isn't showing at the end either (returns `None` when running in a notebook). Will update when I have a solution.

**Comment by alexonab** [comment]
It looks like commenting out lines 108 and 109 in alpacastore.py works also.  I don't see the need for the event loop when calling conn.run.

**Comment by kevinmarkwardt** [comment]
The only way I could get this working is by updating the stream2.py as well but I changed it like this

```
# /site-packages/alpaca_trade_api/stream2.py
class StreamConn(object):
    def __init__(self, key_id=None, secret_key=None, base_url=None):
        self._key_id, self._secret_key = get_credentials(key_id, secret_key)
        base_url = re.sub(r'^http', 'ws', base_url or get_base_url())
        self._endpoint = base_url + '/stream'
        self._handlers = {}
        self._handler_symbols = {}
        self._base_url = base_url
        self._ws = None
        self.polygon = None

        # Add try block for get_event_loop()
        # If no current loop then create one
        try:
            self.loop = asyncio.get_event_loop()
        except:
            self.loop = asyncio.new_event_loop()
            asyncio.set_event_loop(self.loop)
```
TO
```
# /site-packages/alpaca_trade_api/stream2.py
class StreamConn(object):
    def __init__(self, key_id=None, secret_key=None, base_url=None):
        self._key_id, self._secret_key = get_credentials(key_id, secret_key)
        base_url = re.sub(r'^http', 'ws', base_url or get_base_url())
        self._endpoint = base_url + '/stream'
        self._handlers = {}
        self._handler_symbols = {}
        self._base_url = base_url
        self._ws = None
        self.polygon = None

        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)
```
Setting a new event loop and then setting that new one as the current event loop.  Once I did that the threads connected and data streamed in.  Hope this helps someone else.

**Comment by shlomikushchi** [comment]
this issue should be resolved with the updated version on pypi.
let me know if you still encounter issues.
please note - you must have a funded account to do paper/live trading.
you could do backtesting by getting the data not through polygon (polygon access requires a funded account)
let me know if there are still issues
