### ISSUE TITLE
get_account() return a string, but a number is needed

### ISSUE THREAD

**Issue by fjctp** [alpacahq/alpaca-backtrader-api#14]
REST API: `get_account()` return cash and portfolio as a string, but a number is needed to create a line in a broker.

see `_t_account()` in AlpacaStore.py

REST API return:
```
{
    ...
    "cash": "89120.36",
    "portfolio_value": "99371.06",
    ...
}
```

Exception:
```
Traceback (most recent call last):
  File ".\demo_backtest.py", line 56, in <module>
    cerebro.run(exactbars=False)
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\cerebro.py", line 1630, in _runnext
    strat._next()
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\strategy.py", line 351, in _next
    self._next_observers(minperstatus)
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\strategy.py", line 379, in _next_observers
    observer._next()
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\lineiterator.py", line 282, in _next
    self.nextstart()  # only called for the 1st value
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\lineiterator.py", line 347, in nextstart
    self.next()
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\observers\broker.py", line 114, in next
    self.lines.value[0] = value = self._owner.broker.getvalue()
  File "C:\Users\Test\Miniconda3\envs\alpaca-trade\lib\site-packages\backtrader\linebuffer.py", line 222, in __setitem__
    self.array[self.idx + ago] = value
```

**Comment by shlomikushchi** [comment]
this is not related to alpaca_backtrader_api. it should be in https://github.com/alpacahq/alpaca-trade-api-python

BUT, it could be done through alpaca_backtrader_api like so:
```
store = alpaca_backtrader_api.AlpacaStore(
    key_id=ALPACA_API_KEY,
    secret_key=ALPACA_SECRET_KEY,
    paper=ALPACA_PAPER
)

store.oapi.get_account()
```

and when doing that we could this issue is now resolved.

**Comment by shlomikushchi** [comment]
this is not relevant to this repo. I opened a PR for this issue in the relevant repo:
https://github.com/alpacahq/alpaca-trade-api-python/pull/174
