### ISSUE TITLE
Paper trading broken- due to wrong data type for amounts or size (str vs int or float)

### ISSUE THREAD

**Issue by sudopk** [alpacahq/alpaca-backtrader-api#33]
Versions:
```
alpaca-backtrader-api==0.6
alpaca-trade-api==0.46
```

Try example at (with `ALPACA_PAPER = True`):

https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/sma_crossover_strategy.py

Hit error:
```
Traceback (most recent call last):
  File "sma_crossover_strategy.py", line 81, in <module>
    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
TypeError: must be real number, not str
```

Change the line to:

```
 print('Starting Portfolio Value: %s' % cerebro.broker.getvalue())
```

Try again and hit:
```
Exception in thread Thread-2:
Traceback (most recent call last):
File "lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 316, in _t_streaming_events
base_url=self.p.base_url)
File "lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 94, in __init__
self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
File "lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 27, in __init__
self.loop = asyncio.get_event_loop()
File "lib/python3.6/asyncio/events.py", line 694, in get_event_loop
return get_event_loop_policy().get_event_loop()
File "lib/python3.6/asyncio/events.py", line 602, in get_event_loop
% threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2'.

  Traceback (most recent call last):
File "sma_crossover_strategy.py", line 82, in <module>
                                                                                   cerebro.run()
File "lib/python3.6/site-packages/backtrader/cerebro.py", line 1127, in run
runstrat = self.runstrategies(iterstrat)
File "lib/python3.6/site-packages/backtrader/cerebro.py", line 1187, in runstrategies
self._broker.start()
File "lib/python3.6/site-packages/alpaca_backtrader_api/alpacabroker.py", line 107, in start
self.positions = self.update_positions()
File "lib/python3.6/site-packages/alpaca_backtrader_api/alpacabroker.py", line 97, in update_positions
broker_positions_mapped_by_symbol[name].avg_entry_price
File "lib/python3.6/site-packages/backtrader/position.py", line 64, in __init__
self.set(size, price)
File "lib/python3.6/site-packages/backtrader/position.py", line 75, in set
if self.size > 0:
  TypeError: '>' not supported between instances of 'str' and 'int'
```

Basically seems like the alpaca broker implementation doesn't convert the str values to correct data type like float or int

**Comment by shlomikushchi** [comment]
thanks for the issue. 
you have here 2 types of errors:
1. string-float conversion (like what you fixed yourself) - the api returns floats as strings and we need to convert them back to float/int. I fixed it in the repo and you can pull it from the master branch. pypi version will be updated soon.
2. asyncio event loop in the alpaca api. I will create a separate PR for that, but releasing the api sdk takes more time. for now, this is what you do:

* open `alpaca-trade-api-python/alpaca_trade_api/stream2.py` (it's probably in your site-packages)
* go to line 28:
`except websockets.WebSocketException as wse:`
* change it to:
`except (websockets.WebSocketException, RuntimeError) as wse:`

note: to install from the master branch in github do this:
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api`

**Comment by shlomikushchi** [comment]
closing this issue. let me know if there are still problems regarding this solution and I will re-open it.
