### ISSUE TITLE
Error running samples - Paper Trading

### ISSUE THREAD

**Issue by tylercollins590** [alpacahq/alpaca-backtrader-api#40]
I've added my credentials to the samples and I'm run the samples and set paper trading to True. This occurs on both windows and linux

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 316, in _t_streaming_events
    base_url=self.p.base_url)
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 94, in __init__
    self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\site-packages\alpaca_trade_api\stream2.py", line 27, in __init__
    self.loop = asyncio.get_event_loop()
  File "C:\Users\Tyler Collins\anaconda3\envs\AlgoTrading\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2'.`

**Comment by shlomikushchi** [comment]
first you got to make sure that you have a funded account to run paper/live trading for now (it will change soon with the new API)

there's a fix for this issue not yet on pypi. you could install it like this:
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api@v0.7.1 -U`

**Comment by tylercollins590** [comment]
This worked. Thank you.
