### ISSUE TITLE
RuntimeError: There is no current event loop in thread

### ISSUE THREAD

**Issue by kr011** [alpacahq/alpaca-backtrader-api#42]
When trying to go live, I am getting the following error. This was previously brought up by people but dismissed as caused because a live account is needed (paper account can't access polygon's api). I have opened a live account to get this working but still the same issue. Note that I have confirmed by live account API key ID works fine against Polygon's end point when I try it directly.

I have the latest package installed:
```
pip freeze | findstr alpaca-backtrader-api
alpaca-backtrader-api==0.7
```

Here is the code I am running:
```
# This is the example code from the repo's README
import alpaca_backtrader_api
import backtrader as bt
from datetime import datetime
from secrets import alpaca_live_id, alpaca_live_key

class TestAlgo(bt.Strategy):
    def next(self):
        dt = self.datetime.datetime(ago=0)
        for d in self.datas:
            dn = d._name
            print(dt, dn, d.close[0])

if __name__ == '__main__':
    cerebro = bt.Cerebro()
    cerebro.addstrategy(TestAlgo)

    store = alpaca_backtrader_api.AlpacaStore(
        key_id=alpaca_live_id,
        secret_key=alpaca_live_key,
        paper=False
    )

    # or just alpaca_backtrader_api.AlpacaBroker()
    broker = store.getbroker()
    cerebro.setbroker(broker)

    DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
    data0 = DataFactory(dataname='AAPL',
                        historical=False,
                        timeframe=bt.TimeFrame.Minutes)
    cerebro.adddata(data0)

    print('Starting Portfolio Value: {}'.format(cerebro.broker.getvalue()))
    cerebro.run()
    print('Final Portfolio Value: {}'.format(cerebro.broker.getvalue()))
    cerebro.plot()
```

Here is the output I am getting:
```
Starting Portfolio Value: 1.0
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\kr\Miniconda3\envs\kr\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 316, in _t_streaming_events
    base_url=self.p.base_url)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 94, in __init__
    self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_trade_api\stream2.py", line 27, in __init__
    self.loop = asyncio.get_event_loop()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\asyncio\events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\asyncio\events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-7'.

Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\kr\Miniconda3\envs\kr\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 449, in _t_streaming_prices
    base_url=self.p.base_url)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_backtrader_api\alpacastore.py", line 94, in __init__
    self.conn = tradeapi.StreamConn(api_key, api_secret, base_url)
  File "C:\Users\kr\Miniconda3\envs\kr\lib\site-packages\alpaca_trade_api\stream2.py", line 27, in __init__
    self.loop = asyncio.get_event_loop()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\asyncio\events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\kr\Miniconda3\envs\kr\lib\asyncio\events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-11'.
```

**Comment by shlomikushchi** [comment]
update to version v0.7.1
not yet on pypi. you can install it from github like this:
`pip install git+https://github.com/alpacahq/alpaca-backtrader-api@v0.7.1`
