### ISSUE TITLE
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)

### ISSUE THREAD

**Issue by x777** [alpacahq/alpaca-backtrader-api#45]
I try paper trading with my own live feed using alpaca-backtrader-api. When I do resample for this data feed, I received message:

`sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)…`

Sometimes it starts normally, but often no at all. 

When disable alpaca broker, data feed working well.

**Comment by shlomikushchi** [comment]
so this is a known issue. it happens when doing a rest request to the servers too often. I'm working on resolving it and it will be fixed in the next release.
in any case, it doesn't influence your code flow. so it does appear on the console, but your code should work with no issue.

**Comment by x777** [comment]
@shlomikushchi Ok, but I don't see my logs from algorithm, so I am not sure that it's working.

**Comment by shlomikushchi** [comment]
which data source are you using? alpaca data api or polygon?

**Comment by x777** [comment]
@shlomikushchi polygon with AlpacaStore. Without Alpaca broker works good.

**Comment by shlomikushchi** [comment]
are you using an IDE? try putting a breakpoint in `next()` of you strategy file. let's see if it gets there.

**Comment by x777** [comment]
@shlomikushchi yes. Put breakpoint. 
I see only: "Starting Portfolio Value: 99695.46" and waiting...then after again:
`sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)`

**Comment by shlomikushchi** [comment]
ok I understand. I will try to debug this soon and will let you know.

**Comment by shlomikushchi** [comment]
could you check which version of alpaca-trade-api-python you have installed? 
just run this: `pip freeze| grep alpaca-trade-api-python`

**Comment by x777** [comment]
@shlomikushchi `pip freeze| grep alpaca-trade-api-python` - no such library.
Only this:

```
alpaca-backtrader-api==0.7
alpaca-trade-api==0.46
```

**Comment by shlomikushchi** [comment]
could you update alpaca-trade-api to the latest version and try again?

**Comment by x777** [comment]
```
/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/alpaca_trade_api/stream2.py:151: UserWarning: Discarding nonzero nanoseconds in conversion
  await handler(self, channel, ent)
```

and now even without alpaca broker I can't use it, looks I need downgrade it?

```
Traceback (most recent call last):
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/sslproto.py", line 650, in _process_write_backlog
    self._transport.write(chunk)
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/selector_events.py", line 756, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/selector_events.py", line 634, in _fatal_error
    self._force_close(exc)
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/selector_events.py", line 646, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/base_events.py", line 595, in call_soon
    self._check_closed()
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/base_events.py", line 381, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py:818> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f19677c7b58>()]> cb=[<TaskWakeupMethWrapper object at 0x7f19677c7dc8>()]>
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.keepalive_ping() done, defined at /home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py:1103> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f19677c7d38>()]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7f195f4600a0>
Traceback (most recent call last):
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py", line 1206, in close_connection
    if await self.wait_for_connection_lost():
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py", line 1229, in wait_for_connection_lost
    loop=self.loop if sys.version_info[:2] < (3, 8) else None,
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/tasks.py", line 342, in wait_for
    timeout_handle = loop.call_later(timeout, _release_waiter, waiter)
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/base_events.py", line 564, in call_later
    timer = self.call_at(self.time() + delay, callback, *args)
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/base_events.py", line 574, in call_at
    self._check_closed()
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/asyncio/base_events.py", line 381, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() done, defined at /home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py:1153> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/websockets/protocol.py:818> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f19677c7b58>()]> cb=[<TaskWakeupMethWrapper object at 0x7f19677c7dc8>()]>>
^CStopping Backtrader
Traceback (most recent call last):
  File "alpaca.py", line 127, in <module>
    cerebro.plot(style='candlestick')
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/backtrader/cerebro.py", line 996, in plot
    plotter.show()
  File "/home/x777/anaconda3/envs/env_backtrader/lib/python3.6/site-packages/backtrader/plot/plot.py", line 814, in show
    self.mpyplot.show()
```

**Comment by x777** [comment]
I downgraded alpaca-trader-api to 0.46 and I had to upgraded alpaca-backtrader-api to 0.7.1 because event loop error, that I didn't see before.

**Comment by shlomikushchi** [comment]
ok, just remember to update all packages when we release the new version

**Comment by x777** [comment]
> ok, just remember to update all packages when we release the new version

I mean with old versions. With new now working at all. But I will try with new env from scratch.

**Comment by shlomikushchi** [comment]
check out this version and let me know if it works now: try the new version and check if you still get this error: https://github.com/alpacahq/alpaca-backtrader-api/releases/tag/v0.8.0

**Comment by x777** [comment]
@shlomikushchi what version of python I need? I can't install 0.8.0 even from scratch.

**Comment by x777** [comment]
@shlomikushchi 0.8.0 could not find version.

**Comment by shlomikushchi** [comment]
try this: `pip install git+https://github.com/alpacahq/alpaca-backtrader-api@v0.8.0`

**Comment by x777** [comment]
pip freeze:
```
alpaca-backtrader-api==0.8.0
alpaca-trade-api==0.48
```
Something new in logs but "sleeping" looks like the same:
```
Starting Portfolio Value: 99693.46
/home/x777/anaconda3/envs/env_alpaca/lib/python3.6/site-packages/alpaca_trade_api/stream2.py:151: UserWarning: Discarding nonzero nanoseconds in conversion
  await handler(self, channel, ent)
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)..
```

```
 store = alpaca_backtrader_api.AlpacaStore(
        key_id=ALPACA_API_KEY,
        secret_key=ALPACA_SECRET_KEY,
        paper=True
    )

data = DataFactory(
        dataname='SPY',
        tz=timezone,
        timeframe=bt.TimeFrame.Minutes,
        compression=1,
        fromdate=pd.Timestamp('2020-5-11'),
        historical=False
        )
```
Then, I starting resampling time frames.

**Comment by x777** [comment]
After about 1 minute, it started, but sometimes I receiving `"sleep 3 seconds"`.
As I understand, I am using my polygon key by default, right?

**Comment by shlomikushchi** [comment]
the `sleep 3 seconds and retrying ` message is annoying but should not affect your execution.
I will fix it soon.
now it works as expected?
by default you use the alpaca data stream.
you could provide to use the polygon stream
keys should be the same 
polygon stream could only be used in funded accounts.

**Comment by x777** [comment]
`export POLYGON_KEY_ID` is still works in 0.8.0 release?

**Comment by shlomikushchi** [comment]
if you want to use the polygon stream. just make sure to pass `usePolygon`

**Comment by x777** [comment]
I don't understand why you said that "sleep 3 second" not affect to algorithm. For example, If I set up `fromdate` to few days ago (I must because I need data to my SMAs), it loads very slow vs without alpaca broker.
Few days loading took about 30 minutes! It's normal? Maybe I am doing something wrong?

**Comment by shlomikushchi** [comment]
IMO these are unrelated issues. let's try something.  change line 152 in alpaca_backtrader_api/alpacabroker from this:
`self.value = float(self.o.oapi.get_account().portfolio_value)`
to this: 
`self.value = float(self.o.get_value())`
it will make the 3 seconds log line to disappear. let's see if your other issue disappears as well.

**Comment by x777** [comment]
`sleep 3 second...` not disappear, but looks like algorithm is loaded data much faster. Will see on trading session. Anyway, between logs I see sometimes this message.

**Comment by x777** [comment]
Looks like Alpaca Data very rare data feed. Bad news again.

Alpaca Data chart:
![image](https://user-images.githubusercontent.com/4421831/82119790-4d1a4800-974f-11ea-9bef-88e2ecfa48da.png)

Polygon Data chart:
![image](https://user-images.githubusercontent.com/4421831/82119830-9e2a3c00-974f-11ea-9622-d79c1416bb7e.png)

**Comment by shlomikushchi** [comment]
so, I'm not sure what I see in the graphs. could you explain? are you still experiencing issues?

**Comment by x777** [comment]
Alpaca Data chart shows that data not loading because (I think so) no data or very rare (dots in example) and moving can't be calculated. It's about data quality.

About issues yes - I've tried using with all your comments lines and uncomments, but it's freezing - not loading data or very slow and no matter with Alpaca data or Polygon. Maybe with Polygon faster soe times. 

Looks like not many people use this library, so we can't analyze problem on my side or not.
Now, I am using old version of packages only.

**Comment by shlomikushchi** [comment]
does it happen with polygon as well? code for polygon should be the same. 
does it happen with every symbol you try? for instance the example code works with AAPL and this is the data calls I get right now:
![image](https://user-images.githubusercontent.com/7924802/82454945-129c0c80-9abb-11ea-9b83-6dd1aee4f2ed.png)

so basically every second.

**Comment by x777** [comment]
I think all problems begin after adding resample(). Without it works good, better is 100%. But without resample no sense. Did you try add few resample() and test?

**Comment by shlomikushchi** [comment]
no I haven't. could you give me a simple use case based on the sma_crossover_strategy?

**Comment by x777** [comment]
I am using this code in constructor:
        ```
# moving average for 120 min
        self.sma_20 = bt.ind.SMA(self.data1, period=20)
             
        # moving average for 120 min
        self.sma_20_120 = bt.ind.SMA(self.data2, period=20)
```

And this code for resampling:
   ```
#data
   cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=1)
    # data1
     cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=20, name='data_30m')
    # data2
    cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=120, name='data_120m')
```

In `next()` you can simple log self.sma_20 and  self.sma_20_120.

**Comment by x777** [comment]
I am using this code in constructor:
```
#moving average for 120 min
        self.sma_20 = bt.ind.SMA(self.data1, period=20)
#moving average for 120 min
        self.sma_20_120 = bt.ind.SMA(self.data2, period=20)

```
And this code for resampling:

   ```
 #data
   cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=1)
    #data1
     cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=20, name='data_30m')
    #data2
    cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=120, name='data_120m')
```


In `next()` you can simple log self.sma_20 and  self.sma_20_120.

**Comment by shlomikushchi** [comment]
so next is still called every second:
![image](https://user-images.githubusercontent.com/7924802/82462673-8abb0000-9ac4-11ea-824d-aed2d59899dd.png)



but this is the data in each data:
![image](https://user-images.githubusercontent.com/7924802/82462626-7bd44d80-9ac4-11ea-9a93-27e03c28caed.png)

you would expect different data in each array?

**Comment by x777** [comment]
First added `resample()` is what `nex()` will iterate in my experience. Then, try simple `log()` for any ticker value of `self.sma_20` and `self.sma_20_10`:

```
def log(self, txt, dt=None):
        ''' Logging function for this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        if isinstance(dt, float):
            dt = bt.num2date(dt)
        print('%s, %s, %s' % (dt.isoformat(), self.datetime.time(), txt))
```

**Comment by shlomikushchi** [comment]
![image](https://user-images.githubusercontent.com/7924802/82465957-7e38a680-9ac8-11ea-96ed-68be718a84a1.png)
 this is what I get with the log method.

it loads in about a minute.
no sleep messages. and I don't use the patch (`self.value = float(self.o.get_value())`) I suggested to you
and no `"sleep 3 seconds"`

**Comment by x777** [comment]
Can you provide `DataFactory()` params you are using?

**Comment by x777** [comment]
If I am using this code to log SMA:
```
DataFactory = store.getdata  # or use alpaca_backtrader_api.AlpacaData
    data = DataFactory(
        dataname=args.ticker,
        tz=timezone,
        timeframe=bt.TimeFrame.Minutes,
        compression=1,
        fromdate=pd.Timestamp('2020-5-1'),
        historical=False)
```
On the vide speed of loading:

https://vimeo.com/420733579

Without  `fromdate=pd.Timestamp('2020-5-1'),` it's not loading at all. I don't know if it needed, maybe for SMA it loads data automatically?

**Comment by shlomikushchi** [comment]
this is the data factory I am using:
```py 
DataFactory(dataname='AAPL',
                            historical=False,
                            timeframe=bt.TimeFrame.Days)
        # or just alpaca_backtrader_api.AlpacaBroker()
        broker = store.getbroker()
        cerebro.setbroker(broker)
```
and basically the entire stratefy code is in the sample folder of the repo

**Comment by shlomikushchi** [comment]
also changing to `timeframe=bt.TimeFrame.MInutes` works the same way

**Comment by shlomikushchi** [comment]
so the difference is the start_date. once added it takes time to load previous data. but that also makes sense, no?

**Comment by x777** [comment]
Why without Alpaca broker it's much faster - in example above from 2020-5-1 it takes about few seconds vs hour and more with Alpaca broker?

**Comment by shlomikushchi** [comment]
that is weird because the data source is the same

**Comment by x777** [comment]
Yes, but anyway I appreciate for this library because it was simpler way to start backtesting and also live trading (with side execution)  with polygon.io data.

**Comment by shlomikushchi** [comment]
this package wraps the python sdk.
you may look directly at the sdk
https://github.com/alpacahq/alpaca-trade-api-python
and the example code
it is another approach you could take

**Comment by alias-noa** [comment]
I'm having this problem now, but last week I ran this same code for paper trade and it worked fine....strange.

**Comment by alias-noa** [comment]
I'm getting: sleep 3 seconds and retrying https://api.alpaca.markets/v2/account 3 more time(s)...

If I click the link it gives:  

{"code":40110000,"message":"access key verification failed : access key not found (Code = 40110000)"}

It happens in both paper trading and live mode, but not in backtests.  Anyone know what's going on?

**Comment by shlomikushchi** [comment]
when you run a backtest you are not connected to the broker so it makes sense it doesn't happen in that case
try pulling the latest code from the master branch and run it again today

**Comment by alias-noa** [comment]
That worked, thx!  I just worry that in the future i'm going to be running it live and it's going to just stop working or something.  Any idea what causes problems like that or if they can happen while you're running it live on a real $$ account?

**Comment by shlomikushchi** [comment]
first of all always start by paper trading for a while, making sure your setup works
secondly, follow the issue page of the package, it's active and we try to make sure any issue is handled
so make sure you're updated with the latest version

**Comment by alias-noa** [comment]
Nevermind, it didn't work.  The market was just closed :/

**Comment by alias-noa** [comment]
Yes that's how I found this, the issues page.  I saw this guy had the same issue but it doesn't seem like it was ever resolved.

**Comment by alias-noa** [comment]
I changed usePolygon to False and didn't get the error anymore.  Idk what it uses if not polygon though.  Maybe this is a polygon related error? I don't have money in my real $$ account yet, it's pending, so maybe I can't use polygon yet.  I sent $5 to it to see if that's why i'm having this issue.

**Comment by shlomikushchi** [comment]
we have 2 data sources - polygon and alpaca.
you can only use the polygon data source if you have a funded account
the alpaca data source is free

**Comment by alias-noa** [comment]
You know what, it's not Polygon.  It's something wrong with my strategy.  I tried one of the sample strategies and it works fine with polygon and paper trading.  I didn't find the problem specifically but it was an error on my part in the strategy.  Thanks for the quick responses though!

**Comment by alias-noa** [comment]
Okay this seems to be causing it. I'm trying to use 5 minute candles, is this not the proper way? : 

`TRADE_LIVE = True
TICKER_SYMBOL = 'AAPL'
CHART_RESOLUTION = 5        # minutes per candle
BACKTEST_START_MONTH = 1
BACKTEST_START_DAY = 1
BACKTEST_START_YEAR = 2019`

`    if TRADE_LIVE:
        data = DataFactory(dataname=TICKER_SYMBOL,
                           historical=False,
                           timeframe=bt.TimeFrame.Minutes, compression=CHART_RESOLUTION)
        # or just alpaca_backtrader_api.AlpacaBroker()
        broker = store.getbroker()
        cerebro.setbroker(broker)
    else:
        data = DataFactory(dataname=TICKER_SYMBOL, historical=True, fromdate=datetime(
            BACKTEST_START_YEAR, BACKTEST_START_MONTH, BACKTEST_START_DAY), timeframe=bt.TimeFrame.Minutes,
                           compression=CHART_RESOLUTION)`

**Comment by alias-noa** [comment]
Wow code format looks awful on here, will try to fix

**Comment by alias-noa** [comment]
I'm trying to use 5 minute candles but this code seems to be giving me that sleep 3 seconds and retrying error:

TRADE_LIVE = True
TICKER_SYMBOL = 'AAPL'
CHART_RESOLUTION = 5        # minutes per candle
BACKTEST_START_MONTH = 1
BACKTEST_START_DAY = 1
BACKTEST_START_YEAR = 2019

[https://i.imgur.com/Df5yDVL.png](url)
![image](https://user-images.githubusercontent.com/16172321/85867711-4bed2980-b797-11ea-88f5-61f5b24412dd.png)

**Comment by alias-noa** [comment]
When I change bt.TimeFrame.Minutes to Days the error goes away...so seems to be something to do with bt.TimeFrame.Minutes

**Comment by alias-noa** [comment]
Is cerebro.setbroker important?  I got rid of that and now when I run it live I don't get the error and it prints price for every tick when running live

**Comment by alias-noa** [comment]
I think maybe they forgot to program compression into it or something.  the parameter isn't even being used.  I don't want to try to fix it because i'm not that good at this stuff and don't want to mess it up :/ https://i.imgur.com/kGBLARR.png

**Comment by shlomikushchi** [comment]
you are trying to get minute data for a year and a half, that could be a problem.
check the docs, to see if you can find the limitations (polygon docs if you're using polygon and alpaca's docs otherwise)

**Comment by alias-noa** [comment]
OH that makes sense.  I have had problems doing that with other frameworks too.  Thanks I have been really frustrated trying to figure this out.

**Comment by alias-noa** [comment]
Actually i'm not sure if that was even the problem.  I deleted all alpaca and backtrader folders, everything related to either of them, then just unzipped this back into the same folder and now it no longer gives me that error.  Very odd.  I had an alpaca api folder as well (without backtrader) and I think that was somehow conflicting with this.

**Comment by shlomikushchi** [comment]
maybe you installed things under the same virtual environment. try using a clean virtual env

**Comment by shlomikushchi** [comment]
closing due to lack of activity

**Comment by x777** [comment]
New environment, pip freeze:
```
alpaca-backtrader-api==0.10.1
alpaca-trade-api==0.50.1
backtrader==1.9.76.123
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
idna==2.10
kiwisolver==1.2.0
matplotlib==3.3.2
numpy==1.19.2
pandas==1.1.3
Pillow==7.2.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
six==1.15.0
toolz==0.11.1
trading-calendars==1.11.11
urllib3==1.25.10
websocket-client==0.57.0
websockets==8.1
```
Trying to use this sample code https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/strategy_sma_crossover.py, but with one difference, instead of bt.TimeFrame.Days I am trying  bt.TimeFrame.Minutes:

```
data0 = DataFactory(dataname=symbol,
                            historical=False,
                            **timeframe=bt.TimeFrame.Minutes**,
                            backfill_start=True,                    
                            )```  

And looks like forever logging:
```
Starting Portfolio Value: 99920.71
***** DATA NOTIF: DELAYED
2020-10-08 10:55:41,651 connected to: wss://paper-api.alpaca.markets/stream
2020-10-08 10:55:42,294 connected to: wss://data.alpaca.markets/stream
2020-10-08 10:56:39,196 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:56:47,027 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:56:55,404 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:03,546 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:13,243 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:22,087 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:29,888 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:39,282 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:47,317 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:57:55,757 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:04,196 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:04,489 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:14,343 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:22,433 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:31,479 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
2020-10-08 10:58:39,858 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
```

**Comment by x777** [comment]
> New environment, pip freeze:
> 
> ```
> alpaca-backtrader-api==0.10.1
> alpaca-trade-api==0.50.1
> backtrader==1.9.76.123
> certifi==2020.6.20
> chardet==3.0.4
> cycler==0.10.0
> idna==2.10
> kiwisolver==1.2.0
> matplotlib==3.3.2
> numpy==1.19.2
> pandas==1.1.3
> Pillow==7.2.0
> pyparsing==2.4.7
> python-dateutil==2.8.1
> pytz==2020.1
> requests==2.24.0
> six==1.15.0
> toolz==0.11.1
> trading-calendars==1.11.11
> urllib3==1.25.10
> websocket-client==0.57.0
> websockets==8.1
> ```
> 
> Trying to use this sample code https://github.com/alpacahq/alpaca-backtrader-api/blob/master/sample/strategy_sma_crossover.py, but with one difference, instead of bt.TimeFrame.Days I am trying bt.TimeFrame.Minutes:
> 
> ```
> data0 = DataFactory(dataname=symbol,
>                             historical=False,
>                             timeframe=bt.TimeFrame.Minutes,
>                             backfill_start=True,                    
>                             )
> ```
> 
> And looks like forever logging:
> 
> ```
> Starting Portfolio Value: 99920.71
> ***** DATA NOTIF: DELAYED
> 2020-10-08 10:55:41,651 connected to: wss://paper-api.alpaca.markets/stream
> 2020-10-08 10:55:42,294 connected to: wss://data.alpaca.markets/stream
> 2020-10-08 10:56:39,196 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:56:47,027 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:56:55,404 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:03,546 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:13,243 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:22,087 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:29,888 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:39,282 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:47,317 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:57:55,757 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:04,196 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:04,489 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:14,343 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:22,433 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:31,479 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> 2020-10-08 10:58:39,858 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
> ```

What I am doing wrong?

**Comment by x777** [comment]
What I am doing wrong?
