### ISSUE TITLE
concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by jtbales** [alpacahq/alpaca-backtrader-api#54]
Sometime after my live paper trading program reaches data.status of LIVE I get this error.

```
May 28 11:22:12 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
May 28 11:22:16 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
May 28 11:22:16 sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/account 3 more time(s)...
May 28 11:22:20 Reached LIVE data
May 28 11:41:59 Exception in thread Thread-6:
May 28 11:41:59 Traceback (most recent call last):
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
May 28 11:41:59     self.run()
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
May 28 11:41:59     self._target(*self._args, **self._kwargs)
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 483, in _t_streaming_prices
May 28 11:41:59     streamer.run()
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
May 28 11:41:59     self.conn.run(channels)
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 276, in run
May 28 11:41:59     loop.run_until_complete(self.consume())
May 28 11:41:59   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
May 28 11:41:59     return future.result()
May 28 11:41:59 concurrent.futures._base.CancelledError
May 28 11:41:59 
May 28 12:08:07 WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
May 28 12:08:07 Exception in thread Thread-2:
May 28 12:08:07 Traceback (most recent call last):
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/threading.py", line 916, in _bootstrap_inner
May 28 12:08:07     self.run()
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/threading.py", line 864, in run
May 28 12:08:07     self._target(*self._args, **self._kwargs)
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 341, in _t_streaming_events
May 28 12:08:07     streamer.run()
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
May 28 12:08:07     self.conn.run(channels)
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 276, in run
May 28 12:08:07     loop.run_until_complete(self.consume())
May 28 12:08:07   File "/app/.heroku/python/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
May 28 12:08:07     return future.result()
May 28 12:08:07 concurrent.futures._base.CancelledError
```

This code in the strategy logs the switch to LIVE 
```
    def notify_data(self, data, status, *args, **kwargs):
        if status == data.LIVE:
            print("Reached LIVE data")
            self.reached_live_data = True
```

This error happens eventually every time I run it live.

This occurred when using the latest stable release and using `git+https://github.com/alpacahq/alpaca-backtrader-api`

**Comment by shlomikushchi** [comment]
this is a websocket diconnection error. 
I'm currently trying to fix it with this branch: 
https://github.com/alpacahq/alpaca-trade-api-python/tree/websocket_reconnect
you could install it locally and see if that helps, even before we merge and release it.
do this:
`pip install -U git+https://github.com/alpacahq/alpaca-trade-api-python@websocket_reconnect`

I believe it will help you with that issue

**Comment by jtbales** [comment]
Thanks, I'm using the branch now and will find out during today's market

**Comment by jtbales** [comment]
I ran paper trading live a few times and got the same error. A couple times I even got this error: 

```
Traceback (most recent call last):
  File "./main.py", line 90, in <module>
    main()
  File "./main.py", line 49, in main
    cerebro.run()
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/cerebro.py", line 1298, in runstrategies
    self._runnext(runstrats)
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/cerebro.py", line 1630, in _runnext
    strat._next()
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/strategy.py", line 351, in _next
    self._next_observers(minperstatus)
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/strategy.py", line 379, in _next_observers
    observer._next()
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/lineiterator.py", line 280, in _next
    self.next()
  File "/app/.heroku/python/lib/python3.7/site-packages/backtrader/observers/broker.py", line 110, in next
    self.lines.value[0] = value = self._owner.broker.getvalue()
  File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_backtrader_api/alpacabroker.py", line 152, in getvalue
    self.value = float(self.o.oapi.get_account().portfolio_value)
  File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_trade_api/entity.py", line 29, in __getattr__
    return super().__getattribute__(key)
AttributeError: 'Account' object has no attribute 'portfolio_value'
Process exited with status 1
State changed from up to crashed
```

Not sure if this is related to the branch changes but it's a new error for me. 

Sorry I don't know exactly what's triggering it. I'm going to add more logging to find out what's happening. 
For now all I've recognized is 
1. It consistently throws the `concurrent.futures._base.CancelledError` within 2 hours of starting the app. 
2. With the new branch my logs and activities appear to freeze after it reaches data status LIVE.

**Comment by shlomikushchi** [comment]
the disconnection error is supposed to appear - but the app should recover and continue execution. 
is this what you get?
your other exception is not related. open a new issue for it

**Comment by jtbales** [comment]
They don't appear to reconnect.

One thread fails and it keeps going for 20 minutes
```
Jun 01 11:36:06 WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
Jun 01 11:36:06 Exception in thread Thread-2:
Jun 01 11:36:06 Traceback (most recent call last):
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
Jun 01 11:36:06     self.run()
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/threading.py", line 870, in run
Jun 01 11:36:06     self._target(*self._args, **self._kwargs)
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 341, in _t_streaming_events
Jun 01 11:36:06     streamer.run()
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
Jun 01 11:36:06     self.conn.run(channels)
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 276, in run
Jun 01 11:36:06     loop.run_until_complete(self.consume())
Jun 01 11:36:06   File "/app/.heroku/python/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
Jun 01 11:36:06     return future.result()
Jun 01 11:36:06 concurrent.futures._base.CancelledError
```

Then a second fails and the app stops doing anything
```
Jun 01 11:55:34 Exception in thread Thread-6:
Jun 01 11:55:34 Traceback (most recent call last):
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
Jun 01 11:55:34     self.run()
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/threading.py", line 870, in run
Jun 01 11:55:34     self._target(*self._args, **self._kwargs)
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 483, in _t_streaming_prices
Jun 01 11:55:34     streamer.run()
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
Jun 01 11:55:34     self.conn.run(channels)
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 276, in run
Jun 01 11:55:34     loop.run_until_complete(self.consume())
Jun 01 11:55:34   File "/app/.heroku/python/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
Jun 01 11:55:34     return future.result()
Jun 01 11:55:34 concurrent.futures._base.CancelledError
Jun 01 11:55:34 app/worker.1 
Jun 01 17:05:00 heroku/worker.1 State changed from up to down
```
It always seems to be the case the Thread-2 and Thread-6 eventually go down, don't come back up, and when they both fail the app stops. 

As you can see here from my Heroku build logs, I'm using the branches. Please verify though, I hope I'm just installing incorrectly. 
```
-----> Installing requirements with pip
Collecting git+https://github.com/alpacahq/alpaca-backtrader-api (from -r /tmp/build_45b90d6c97a3e4ae7f0cac6ac09953e9/requirements.txt (line 7))
  Cloning https://github.com/alpacahq/alpaca-backtrader-api to /tmp/pip-req-build-qxgdki86
  Running command git clone -q https://github.com/alpacahq/alpaca-backtrader-api /tmp/pip-req-build-qxgdki86
Collecting git+https://github.com/alpacahq/alpaca-trade-api-python@websocket_reconnect (from -r /tmp/build_45b90d6c97a3e4ae7f0cac6ac09953e9/requirements.txt (line 8))
  Cloning https://github.com/alpacahq/alpaca-trade-api-python (to revision websocket_reconnect) to /tmp/pip-req-build-rbhpty9t
  Running command git clone -q https://github.com/alpacahq/alpaca-trade-api-python /tmp/pip-req-build-rbhpty9t
  Running command git checkout -b websocket_reconnect --track origin/websocket_reconnect
  Switched to a new branch 'websocket_reconnect'
  Branch 'websocket_reconnect' set up to track remote branch 'websocket_reconnect' from 'origin'.
```

**Comment by shlomikushchi** [comment]
1. are you using more than 1 datas in your algo? (more than 1 symbol e.g AAPL and GOOG)
2. run this command: `pip freeze|grep alpaca` I want to see the output
3. you should create a fresh install with a new virtual env installing the requirements fresh that might help

**Comment by jtbales** [comment]
1. Only 1 data for 1 symbol. 
2. 
```
alpaca-backtrader-api==0.8.0
alpaca-trade-api==0.48
```
3. I've tried removing all dependencies locally then re-installing, upgrading dependencies locally, and as for Heroku I see from the build logs that it clears the cache before installing those.

**Comment by shlomikushchi** [comment]
about this issue - I don't experience anything like this so you need to try to provide more information. try to figure out what's going on on that server because it works smoothly here with the updated alpaca-trade-api-python

**Comment by shlomikushchi** [comment]
did you try to execute it locally? do you experience the same issues?

**Comment by jtbales** [comment]
Yes I get the same errors eventually running locally as I do on Heroku.

**Comment by shlomikushchi** [comment]
let's try something.. I'm creating a branch for you with some added resilience to the alpacastore. let's see if that helps.
install it like this: `pip install -U git+https://github.com/alpacahq/alpaca-backtrader-api@more_resilience_for_alpacastore`

now remember, it's ok to get the `concurrent.futures._base.CancelledError` as long as the execution continues.

**Comment by jtbales** [comment]
I tried the branch and it's been stuck doing nothing for a over an hour now

```
...

WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 341, in _t_streaming_events
    streamer.run()
  File "/usr/local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
    self.conn.run(channels)
  File "/usr/local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 276, in run
    loop.run_until_complete(self.consume())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError

('notify_fund --- Cash: 99994.36, Value: 99995.70, Fundvalue: 99995.70, Shares: 1',)
('notify_fund --- Cash: 99993.02, Value: 99995.66, Fundvalue: 99995.66, Shares: 1',)
('notify_fund --- Cash: 99993.02, Value: 99995.58, Fundvalue: 99995.58, Shares: 1',)
('notify_fund --- Cash: 99993.02, Value: 99995.50, Fundvalue: 99995.50, Shares: 1',)
WARNING:root:code = 1006 (connection closed abnormally [internal]), no reason
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 483, in _t_streaming_prices
    streamer.run()
  File "/usr/local/lib/python3.7/site-packages/alpaca_backtrader_api/alpacastore.py", line 132, in run
    self.conn.run(channels)
  File "/usr/local/lib/python3.7/site-packages/alpaca_trade_api/stream2.py", line 276, in run
    loop.run_until_complete(self.consume())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

**Comment by shlomikushchi** [comment]
just making sure you have the most updated python-sdk?
install it like this:
`pip install -U git+https://github.com/alpacahq/alpaca-trade-api-python`

also, let's try one more thing. let's run the example code: `sma_crossover_strategy.py`
are you still getting these errors with the sample code from the repo?

also, a reminder - it is ok to get the `concurrent.futures._base.CancelledError` as long as the script continues its execution

**Comment by shlomikushchi** [comment]
have you tried my seggestions?

**Comment by shlomikushchi** [comment]
closing due to lack of activity
